services:
  app:
    networks:
      - app_payment_network
      - shared_ecommerce_network
    container_name: payment-app
    build:
      context: .
    image: wesley00s/payment-service:latest
    ports:
      - "8082:8082"
    env_file:
      - .env

networks:
  app_payment_network:
    driver: bridge
  shared_ecommerce_network:
    external: true